# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,2,3,4,5])

In [3]:
a

array([1, 2, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [6]:
b=np.array([[1,2,2,3,4,5],[1,2,2,3,4,5]])

In [7]:
b

array([[1, 2, 2, 3, 4, 5],
       [1, 2, 2, 3, 4, 5]])

In [8]:
type(b)

numpy.ndarray

In [22]:
c=np.zeros((2,6))

In [23]:
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
d=c*b

In [25]:
e=np.full((3,3),44)

In [26]:
e

array([[44, 44, 44],
       [44, 44, 44],
       [44, 44, 44]])

In [45]:
import numpy as np
f=np.arange(10,20)

In [48]:
f

array([10])

In [51]:
f=np.arange(10,20,2) ##skip by 2
f

array([10, 12, 14, 16, 18])

In [56]:
g=np.random.randint(100,500,10)## random 10 number between 100 to 500

In [57]:
g

array([268, 367, 477, 301, 402, 458, 421, 449, 285, 379])

In [58]:
print(b)

[[1 2 2 3 4 5]
 [1 2 2 3 4 5]]


In [2]:
import numpy as np

In [3]:
m=np.array([[1,3,4,4],[1,2,4]])
m=np.array([[1,2,2,3,4,5],[1,2,2,3,4,5]])

In [4]:
m

array([[1, 2, 2, 3, 4, 5],
       [1, 2, 2, 3, 4, 5]])

In [6]:
m.shape()=(2,6)
m

SyntaxError: can't assign to function call (<ipython-input-6-e1ace1c60177>, line 1)